# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bubblejump < Formula
  desc "Quickly get shell access to EC2 instances in our VPC"
  homepage "https://github.com/redbubble/bubblejump"
  version "0.4.4"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "http://apt.redbubble.com/bubblejump/v0.4.4/bubblejump_0.4.4_Darwin_x86_64.tar.gz"
      sha256 "8428ff8ff4111afd36165efccdebc5a4fa7781b8bc1658ae374d792ebc825900"
    end
    if Hardware::CPU.arm?
      url "http://apt.redbubble.com/bubblejump/v0.4.4/bubblejump_0.4.4_Darwin_arm64.tar.gz"
      sha256 "02d0c273f3d785f4a7abe4eaa1d20807181d7fb1e78bf18f7ad56b589aae3d3e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://apt.redbubble.com/bubblejump/v0.4.4/bubblejump_0.4.4_Linux_x86_64.tar.gz"
      sha256 "724aa70df658ab0903a42191b5b6301f4c0bc0f6413753497477664c74b819e3"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://apt.redbubble.com/bubblejump/v0.4.4/bubblejump_0.4.4_Linux_arm64.tar.gz"
      sha256 "baf0090f587d0563ea7e71ef0c1fb545775a9cb89fe5d9b2cea40d371bc3cdf2"
    end
  end

  depends_on "yak"

  def install
    bin.install "bubblejump"
    bash_completion.install "bash.completion" => "bubblejump"
    zsh_completion.install "zsh.completion" => "_bubblejump"
  end

  test do
    system "#{bin}/bubblejump version"
  end
end
