# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bubblejump < Formula
  desc "Quickly get shell access to EC2 instances in our VPC"
  homepage "https://github.com/redbubble/bubblejump"
  version "0.8.4"

  depends_on "yak"

  on_macos do
    if Hardware::CPU.arm?
      url "http://apt.redbubble.com/bubblejump/v0.8.4/bubblejump_0.8.4_Darwin_arm64.tar.gz"
      sha256 "a6b3a3d7be3a48e74cab5c5b5b4592fd34556e74e9b0827ab209b278e2d17314"

      def install
        bin.install "bubblejump"
        bash_completion.install "bash.completion" => "bubblejump"
        zsh_completion.install "zsh.completion" => "_bubblejump"
      end
    end
    if Hardware::CPU.intel?
      url "http://apt.redbubble.com/bubblejump/v0.8.4/bubblejump_0.8.4_Darwin_x86_64.tar.gz"
      sha256 "ce46fe8e09cb74c5db12d4f6e0748b38b5b85905f631d4f38a672157a4a41a90"

      def install
        bin.install "bubblejump"
        bash_completion.install "bash.completion" => "bubblejump"
        zsh_completion.install "zsh.completion" => "_bubblejump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://apt.redbubble.com/bubblejump/v0.8.4/bubblejump_0.8.4_Linux_arm64.tar.gz"
      sha256 "afc68f3c15bd35e4164b95f353e2b672071b194d621b2d4a917853874c0a0b9b"

      def install
        bin.install "bubblejump"
        bash_completion.install "bash.completion" => "bubblejump"
        zsh_completion.install "zsh.completion" => "_bubblejump"
      end
    end
    if Hardware::CPU.intel?
      url "http://apt.redbubble.com/bubblejump/v0.8.4/bubblejump_0.8.4_Linux_x86_64.tar.gz"
      sha256 "5c61a44df86a41c022bd11179ddd88fe69738ba98f705d851a389cde3b46a4c6"

      def install
        bin.install "bubblejump"
        bash_completion.install "bash.completion" => "bubblejump"
        zsh_completion.install "zsh.completion" => "_bubblejump"
      end
    end
  end

  def caveats
    <<~EOS
      To configure Bubblejump's SSH ProxyCommand (useful for database connections),
      add the config block to your SSH config:

      bubblejump proxycommand >> ~/.ssh/config
    EOS
  end

  test do
    system "#{bin}/bubblejump version"
  end
end
