# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../s3_downloader.rb"
class Elk < Formula
  desc "Elk, Redbubble's deploy tool."
  homepage "https://github.com/redbubble/elk"
  version "1.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "s3://elk-artefacts/elks/1.0.5/elk_1.0.5_darwin_arm64.tar.gz", :using => S3DownloadStrategy
      sha256 "8e64c62330760210273ff4a5e9bb0d19b3aabef8bd6b2bbf14fe09b48a8e36bb"

      def install
        bin.install "elk"
      end
    end
    if Hardware::CPU.intel?
      url "s3://elk-artefacts/elks/1.0.5/elk_1.0.5_darwin_amd64.tar.gz", :using => S3DownloadStrategy
      sha256 "86d622abaec77a6397f344f445e9a8d00ba2e9566d3aca7627fbcdfa097c6858"

      def install
        bin.install "elk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "s3://elk-artefacts/elks/1.0.5/elk_1.0.5_linux_arm64.tar.gz", :using => S3DownloadStrategy
      sha256 "56fa030ac09b029826e83de8578bc502a27394b0cf1ecadf2aa1f17a9b5a00b6"

      def install
        bin.install "elk"
      end
    end
    if Hardware::CPU.intel?
      url "s3://elk-artefacts/elks/1.0.5/elk_1.0.5_linux_amd64.tar.gz", :using => S3DownloadStrategy
      sha256 "7de8b8a5d85fe213c26171664740513fdc77b7b4d78e07d8aefbf25205983a34"

      def install
        bin.install "elk"
      end
    end
  end

  depends_on "awscli"
  depends_on "redbubble/redbubble/yak"

  test do
    system "#{bin}/elk --version"
  end
end
