# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yak < Formula
  desc "A tool to log in to AWS through Okta"
  homepage "https://github.com/redbubble/yak"
  version "1.6.4"

  depends_on "pinentry-mac"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/redbubble/yak/releases/download/v1.6.4/yak_1.6.4_darwin_arm64.tar.gz"
      sha256 "4a8f143d8519a06f76da3161d49bcf7d6112975d524f65d423e459153fb04540"

      def install
        bin.install "yak"
        bash_completion.install "static/completions/yak.bash" => "yak"
        zsh_completion.install "static/completions/yak.zsh" => "_yak"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/redbubble/yak/releases/download/v1.6.4/yak_1.6.4_darwin_amd64.tar.gz"
      sha256 "a2ebefdaf30550d55ebc6a53fa441c0ea09dbbd7a3fa3a01015a1314eea8a07e"

      def install
        bin.install "yak"
        bash_completion.install "static/completions/yak.bash" => "yak"
        zsh_completion.install "static/completions/yak.zsh" => "_yak"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/redbubble/yak/releases/download/v1.6.4/yak_1.6.4_linux_arm64.tar.gz"
      sha256 "2c02fea448816923da9679dda1bce69d5a7c6515a7a4c29af242cf95be466afb"

      def install
        bin.install "yak"
        bash_completion.install "static/completions/yak.bash" => "yak"
        zsh_completion.install "static/completions/yak.zsh" => "_yak"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/redbubble/yak/releases/download/v1.6.4/yak_1.6.4_linux_amd64.tar.gz"
      sha256 "8045e3836bf57a15f9dbd18557ffa63bb1c385d846f3d676050fd9c9022a1baa"

      def install
        bin.install "yak"
        bash_completion.install "static/completions/yak.bash" => "yak"
        zsh_completion.install "static/completions/yak.zsh" => "_yak"
      end
    end
  end

  test do
    system "#{bin}/yak --help"
  end
end
