# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yak < Formula
  desc "A tool to log in to AWS through Okta"
  homepage "https://github.com/redbubble/yak"
  version "1.6.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/redbubble/yak/releases/download/v1.6.0/yak_1.6.0_darwin_arm64.tar.gz"
      sha256 "9151d0110d5fbf842759089749911ec406590c1e2df651bcdb2b5eff1d213a2a"

      def install
        bin.install "yak"
        bash_completion.install "static/completions/yak.bash" => "yak"
        zsh_completion.install "static/completions/yak.zsh" => "_yak"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/redbubble/yak/releases/download/v1.6.0/yak_1.6.0_darwin_amd64.tar.gz"
      sha256 "5128c522bacddb58ba1aa7949c49d063679db7eb3d58b0afb1dcb72d2e0b609a"

      def install
        bin.install "yak"
        bash_completion.install "static/completions/yak.bash" => "yak"
        zsh_completion.install "static/completions/yak.zsh" => "_yak"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/redbubble/yak/releases/download/v1.6.0/yak_1.6.0_linux_arm64.tar.gz"
      sha256 "7904ca91775875787611943b41f3a6da6b431d4f31e2f6e42705a302fd8e1489"

      def install
        bin.install "yak"
        bash_completion.install "static/completions/yak.bash" => "yak"
        zsh_completion.install "static/completions/yak.zsh" => "_yak"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/redbubble/yak/releases/download/v1.6.0/yak_1.6.0_linux_amd64.tar.gz"
      sha256 "878d98c28a323d28495182c23e8db9bff17d906cfe2a2a23b3d056980b6dc23a"

      def install
        bin.install "yak"
        bash_completion.install "static/completions/yak.bash" => "yak"
        zsh_completion.install "static/completions/yak.zsh" => "_yak"
      end
    end
  end

  depends_on "pinentry-mac"

  test do
    system "#{bin}/yak --help"
  end
end
